server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8091
          predicates:
          - Path=/auth/api/v1/**
        - id: user_service
          uri: http://localhost:8082
          predicates:
          - Path=/users/api/v1/**