server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: Gateway-Service

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

# C?u hình Swagger cho gateway
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Menu Service
        url: /api/menus/v3/api-docs
      - name: Order Service
        url: /api/orders/v3/api-docs
      - name: kitchen-service
        url: /api/kitchens/v3/api-docs
      - name: invoice-service
        url: /api/invoice/v3/api-docs
      - name: reports-service
        url: /api/reports/v3/api-docs
      - name: users-service
        url: /api/users/v3/api-docs
