CREATE TABLE `follows` (
     id CHAR(36) PRIMARY KEY,
     follower_id CHAR(36) NOT NULL,
     followee_id CHAR(36) NOT NULL,
     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
     updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     deleted ENUM('ACTIVE', 'DELETED') DEFAULT 'ACTIVE'
);