spring:
  application:
    name: UsersService-application
  datasource:
    url: jdbc:mysql://localhost:3306/health_social_user
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8082
  servlet:
    context-path: /users/api/v1