spring:
  application:
    name: AuthService-application
  datasource:
    url: jdbc:mysql://localhost:3306/health_social_user
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/SonNS_realm/protocol/openid-connect/certs
  jpa:
    properties:
      hibernate:
        show_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.hibernate.sql: debug

server:
  port: 8091
  servlet:
    context-path: /auth/api/v1

keycloak:
  realm: social_network
  server-url: http://localhost:8080
  client-id: auth_service
  client-secret: Y8RE1aP7ur5inScS5rGcI482a8cKUqel

url:
  permit:
    - path: "/register"
    - path: "/logout"
    - path: "/login"

user-client:
  url: http://localhost:8082/users/api/v1